name: Build NRD SDK
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install windows-sdk-10.0 cmake -y
      - name: Install Vulkan
        run: |
          $ver = (Invoke-WebRequest -Uri "https://vulkan.lunarg.com/sdk/latest.json" | ConvertFrom-Json).windows
          echo Vulkan SDK version $ver
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/$ver/windows/VulkanSDK-$ver-Installer.exe" -OutFile VulkanSDK.exe
          echo Downloaded
          .\VulkanSDK.exe --root C:\VulkanSDK --accept-licenses --default-answer --confirm-command install
      - name: CMake Generate
        run: |
          $Env:VULKAN_SDK = "C:/VulkanSDK/"
          $Env:Path += ";C:/VulkanSDK/Bin"
          mkdir build
          cd build
          cmake .. -DNRD_EMBEDS_DXBC_SHADERS=False -DNRD_EMBEDS_DXIL_SHADERS=False
          cd ..
      - name: Compile
        run: |
          $Env:VULKAN_SDK = "C:/VulkanSDK/"
          $Env:Path += ";C:/VulkanSDK/Bin"
          cd "build"
          cmake --build . --config Release
          cd ..
      - name: Upload NRD SDK as artefact
        uses: actions/upload-artifact@v3
        with:
          name: Windows
          path: _Build
  build-ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name : Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.16.x'
      - name: Install Vulkan SDK
        run: |
          sudo apt install -y wget
          wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-jammy.list http://packages.lunarg.com/vulkan/lunarg-vulkan-jammy.list
          sudo apt update
          sudo apt install -y vulkan-sdk
      - name: CMake Generate
        run: |
          mkdir build
          cd build
          cmake ..
          cd ..
      - name: Compile
        run: |
          cd build
          cmake --build . --config Release
          cd ..
      - name: Upload NRD SDK as artefact
        uses: actions/upload-artifact@v3
        with:
          name: Linux
          path: _Build/
